final/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
 path('admin/', admin.site.urls),
 # "127.0.0.1:8000/polls/" 이후의 URL은 polls/urls.py가 handling
 path('gazua/', include('gazua.urls')),
]

gazua/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'gazua'

urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.first_view, name='first_view'),
    path('ml_analysis/', views.analysis, name='analysis'),
    path('ml_analysis/predict/', views.predict_analysis, name='predict_analysis'),
    path('resource/', views.resource, name='resource'),
    path('aboutus/', views.aboutus, name='aboutus'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gazua/models.py
from django.db import models

# Create your models here.

gazua/views.py
from django.shortcuts import render, redirect
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from .predict_analysis import predict_stock

# Create your views here.

def first_view(request):
    return render(request, 'main/first_view.html', {})

def index(request):
    return render(request, 'main/index.html', {})

def analysis(request):
    return render(request, 'main/ml_analysis.html', {})

def resource(request):
    return render(request, 'main/resource.html', {})


def aboutus(request):
    return render(request, 'main/aboutus.html', {})


def predict_analysis(request):

    revenue = float(request.POST['revenue']) if request.POST['revenue'] != '' else 1965.20
    total_assets = float(request.POST['total_assets']) if request.POST['total_assets'] != '' else 0.26
    tangible_assets = float(request.POST['tangible_assets'])  if request.POST['tangible_assets']  != '' else 0.20
    current_assets = float(request.POST['current_assets']) if request.POST['current_assets'] != '' else 5.1
    inventories = float(request.POST['inventories'])  if request.POST['inventories']  != '' else 2.4
    growth_rate_of_revenue = float(request.POST['growth_rate_of_revenue'])  if request.POST['growth_rate_of_revenue']  != '' else 2.4
    current_ratio = float(request.POST['current_ratio'])  if request.POST['current_ratio']  != '' else 2.4
    print("***")
    quick_ratio = float(request.POST['quick_ratio'])  if request.POST['quick_ratio']  != '' else 2.4
    dept_ratio = float(request.POST['dept_ratio'])  if request.POST['dept_ratio']  != '' else 2.4
    capital_adequacy = float(request.POST['capital_adequacy'])  if request.POST['capital_adequacy']  != '' else 2.4
    operating_margin = float(request.POST['operating_margin'])  if request.POST['operating_margin']  != '' else 2.4
    return_on_equity = float(request.POST['return_on_equity'])  if request.POST['return_on_equity']  != '' else 2.4
    sales_per_person = float(request.POST['sales_per_person'])  if request.POST['sales_per_person']  != '' else 2.4
    fixed_asset_turnover = float(request.POST['fixed_asset_turnover'])  if request.POST['fixed_asset_turnover']  != '' else 2.4
    price_earnings_ratio = float(request.POST['price_earnings_ratio'])  if request.POST['price_earnings_ratio']  != '' else 2.4
    price_bookvalue_ratio = float(request.POST['price_bookvalue_ratio'])  if request.POST['price_bookvalue_ratio']  != '' else 2.4

    data_1d_array = [revenue, total_assets, tangible_assets, current_assets, inventories, growth_rate_of_revenue, current_ratio, quick_ratio, dept_ratio, capital_adequacy, operating_margin, return_on_equity, sales_per_person, fixed_asset_turnover, price_earnings_ratio, price_bookvalue_ratio]

    predict_result = predict_stock(data_1d_array)

    context = {'predict_result' : predict_result}
    return render(request, 'main/ml_analysis_result.html', context)

gazua/templates/main/ml_analysis.html
{%load static%}

<!DOCTYPE html>
<html  >
<head>
  <!-- Site made with Mobirise Website Builder v4.12.4, https://mobirise.com -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v4.12.4, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="/static/main/assets/images/ant-1.png" type="image/x-icon">
  <meta name="description" content="Web Site Creator Description">


  <title>Analysis</title>
  <link rel="stylesheet" href="/static/main/assets/web//static/main/assets/mobirise-icons/mobirise-icons.css">
  <link rel="stylesheet" href="/static/main/assets/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="/static/main/assets/bootstrap/css/bootstrap-grid.min.css">
  <link rel="stylesheet" href="/static/main/assets/bootstrap/css/bootstrap-reboot.min.css">
  <link rel="stylesheet" href="/static/main/assets/tether/tether.min.css">
  <link rel="stylesheet" href="/static/main/assets/dropdown/css/style.css">
  <link rel="stylesheet" href="/static/main/assets/theme/css/style.css">
  <link rel="preload" as="style" href="/static/main/assets/mobirise/css/mbr-additional.css"><link rel="stylesheet" href="/static/main/assets/mobirise/css/mbr-additional.css" type="text/css">



</head>
<body>
  <section class="menu cid-sy0zTxd0AQ" once="menu" id="menu1-9">


    <nav class="navbar navbar-expand beta-menu navbar-dropdown align-items-center navbar-fixed-top navbar-toggleable-sm">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <div class="hamburger">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </div>
        </button>
        <div class="menu-logo">
            <div class="navbar-brand">
                <span class="navbar-logo">
                    <a href="../">
                         <img src="/static/main/assets/images/ant-1.png" alt="Mobirise" title="" style="height: 3.8rem;">
                    </a>
                </span>
                <span class="navbar-caption-wrap"><a class="navbar-caption text-white display-4" href="../">
                        Gazua</a></span>
            </div>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav nav-dropdown" data-app-modern-menu="true"><li class="nav-item">
                    <a class="nav-link link text-white display-4" href="../resource">
                        <span class="mbri-home mbr-iconfont mbr-iconfont-btn"></span>
                        Resource
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link link text-white display-4" href="../aboutus"><span class="mbri-search mbr-iconfont mbr-iconfont-btn"></span>

                        About Us
                    </a>
                </li></ul>
            <div class="navbar-buttons mbr-section-btn"><a class="btn btn-sm btn-primary display-4" href="ml_analysis.html"><span class="mbri-success mbr-iconfont mbr-iconfont-btn"></span>

                    Try It Now!
                </a></div>
        </div>
    </nav>
</section>

    <section class="counters3 counters cid-sy0AacDi98" id="counters3-2">
    <div class="container pt-4 mt-2">

    <form action="{% url 'gazua:predict_analysis' %}" method="POST">
      {% csrf_token %}

      <label for="Revenue">매출액(억)</label>
      <input type="text" id="Revenue" name="revenue" placeholder="ex) 1965.20">
      <br>

      <label for="Total_assets">총자산 증가율</label>
      <input type="text" id="Total_assets" name="total_assets" placeholder="ex) 0.26">
      <br>

      <label for="Tangible_assets">유형자산 증가율</label>
      <input type="text" id="Tangible_assets" name="tangible_assets" placeholder="ex) 0.20">
      <br>

      <label for="Current_assets">유동자산 증가율</label>
      <input type="text" id="Current_assets" name="current_assets" placeholder="ex) 1.4">
      <br>

      <label for="Inventories">재고자산 증가율</label>
      <input type="text" id="Inventories" name="inventories" placeholder="ex) 0.94">
      <br>

      <label for="Growth_rate_of_revenue">매출액 증가율</label>
      <input type="text" id="Growth_rate_of_revenue" name="growth_rate_of_revenue" placeholder="ex) 0.01">
      <br>

      <label for="Current_ratio">유동 비율</label>
      <input type="text" id="Current_ratio" name="current_ratio" placeholder="ex) 0.41">
      <br>

      <label for="Quick_ratio">당좌 비율</label>
      <input type="text" id="Quick_ratio" name="quick_ratio" placeholder="ex) 0.37">
      <br>

      <label for="Dept_ratio">부채 비율</label>
      <input type="text" id="Dept_ratio" name="dept_ratio" placeholder="ex) 1.03">
      <br>

      <label for="Capital_adequacy">자기자본 비율</label>
      <input type="text" id="Capital_adequacy" name="capital_adequacy" placeholder="ex) 0.47">
      <br>

      <label for="Operating_margin">영업이익률</label>
      <input type="text" id="Operating_margin" name="operating_margin" placeholder="ex) 0.12">
      <br>

      <label for="Return_on_equity">자기자본이익률</label>
      <input type="text" id="Return_on_equity" name="return_on_equity" placeholder="ex) 0.03">
      <br>

      <label for="Sales_per_person">종사자 1인당 매출액(억)</label>
      <input type="text" id="Sales_per_person" name="sales_per_person" placeholder="ex) 9.05">
      <br>

      <label for="Fixed_asset_turnover">고정자산 회전율</label>
      <input type="text" id="Fixed_asset_turnover" name="fixed_asset_turnover" placeholder="ex) 0.37">
      <br>

      <label for="Price_earnings_ratio">PER</label>
      <input type="text" id="Price_earnings_ratio" name="price_earnings_ratio" placeholder="ex) 9.05">
      <br>

      <label for="Price_bookvalue_ratio">PBR</label>
      <input type="text" id="Price_bookvalue_ratio" name="price_bookvalue_ratio" placeholder="ex) 0.37">
      <br>

      <button type="submit">Predict!</button>

    </form>

    <p><a href="{% url 'gazua:first_view' %}">Return to home</a></p>

  </div>
</section>


  <section class="engine"><a href="https://mobirise.info/l">free site templates</a></section><script src="/static/main/assets/web//static/main/assets/jquery/jquery.min.js"></script>
  <script src="/static/main/assets/popper/popper.min.js"></script>
  <script src="/static/main/assets/bootstrap/js/bootstrap.min.js"></script>
  <script src="/static/main/assets/tether/tether.min.js"></script>
  <script src="/static/main/assets/smoothscroll/smooth-scroll.js"></script>
  <script src="/static/main/assets/dropdown/js/nav-dropdown.js"></script>
  <script src="/static/main/assets/dropdown/js/navbar-dropdown.js"></script>
  <script src="/static/main/assets/touchswipe/jquery.touch-swipe.min.js"></script>
  <script src="/static/main/assets/theme/js/script.js"></script>


</body>
</html>

gazua/templates/main/ml_analysis_result.html
{%load static%}

<!DOCTYPE html>
<html  >
<head>
  <!-- Site made with Mobirise Website Builder v4.12.4, https://mobirise.com -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v4.12.4, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="/static/main/assets/images/ant-1.png" type="image/x-icon">
  <meta name="description" content="Web Maker Description">


  <title>Result</title>
  <link rel="stylesheet" href="/static/main/assets/web/assets/mobirise-icons/mobirise-icons.css">
  <link rel="stylesheet" href="/static/main/assets/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="/static/main/assets/bootstrap/css/bootstrap-grid.min.css">
  <link rel="stylesheet" href="/static/main/assets/bootstrap/css/bootstrap-reboot.min.css">
  <link rel="stylesheet" href="/static/main/assets/tether/tether.min.css">
  <link rel="stylesheet" href="/static/main/assets/dropdown/css/style.css">
  <link rel="stylesheet" href="/static/main/assets/theme/css/style.css">
  <link rel="preload" as="style" href="/static/main/assets/mobirise/css/mbr-additional.css"><link rel="stylesheet" href="/static/main/assets/mobirise/css/mbr-additional.css" type="text/css">



</head>
<body>

    <section class="menu cid-sy0zTxd0AQ" once="menu" id="menu1-9">


      <nav class="navbar navbar-expand beta-menu navbar-dropdown align-items-center navbar-fixed-top navbar-toggleable-sm">
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <div class="hamburger">
                  <span></span>
                  <span></span>
                  <span></span>
                  <span></span>
              </div>
          </button>
          <div class="menu-logo">
              <div class="navbar-brand">
                  <span class="navbar-logo">
                      <a href="../">
                           <img src="/static/main/assets/images/ant-1.png" alt="Mobirise" title="" style="height: 3.8rem;">
                      </a>
                  </span>
                  <span class="navbar-caption-wrap"><a class="navbar-caption text-white display-4" href="../">
                          Gazua</a></span>
              </div>
          </div>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav nav-dropdown" data-app-modern-menu="true"><li class="nav-item">
                      <a class="nav-link link text-white display-4" href="../../resource">
                          <span class="mbri-home mbr-iconfont mbr-iconfont-btn"></span>
                          Resource
                      </a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link link text-white display-4" href="../../aboutus"><span class="mbri-search mbr-iconfont mbr-iconfont-btn"></span>

                          About Us
                      </a>
                  </li></ul>
              <div class="navbar-buttons mbr-section-btn"><a class="btn btn-sm btn-primary display-4" href="../ml_analysis"><span class="mbri-success mbr-iconfont mbr-iconfont-btn"></span>

                      Try It Now!
                  </a></div>
          </div>
      </nav>
  </section>

<section>
</section>


<div style="padding:80px; background-color: rgb(238, 238, 238)">

</div>


<section class="engine"><a href="https://mobirise.info/l">free website templates</a></section><section class="services2 cid-synto3XlcJ" id="services2-n">
    <!---->

    <!---->
    <!--Overlay-->

    <!--Container-->


    <div class="container">
        <div class="col-md-12">
            <div class="media-container-row">
                <div class="mbr-figure" style="padding:50px; width: 50%;">
                    <img src="{% static 'main/assets/images/'%}{{predict_result}}.png" class="img-subject"/>
                </div>
                <div class="align-left aside-content">
                    <h2 class="mbr-title pt-2 mbr-fonts-style display-2">

                    </h2>
                    <div class="mbr-section-text">
                        <p class="mbr-text text1 pt-2 mbr-light mbr-fonts-style display-5">

                              3년 후 예측 결과 :
                        </p>
                        <p class="mbr-text text2 pt-4 mbr-light mbr-fonts-style display-1">
                            <span class="predicted-class">{{ predict_result }}</span>
                        </p>
                    </div>
                    <!--Btn-->
                    <div class="mbr-section-btn pt-3 align-left">
                        <a href="../" class="btn btn-warning-outline display-4">
                            Try Again
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


  <script src="/static/main/assets/web/assets/jquery/jquery.min.js"></script>
  <script src="/static/main/assets/popper/popper.min.js"></script>
  <script src="/static/main/assets/bootstrap/js/bootstrap.min.js"></script>
  <script src="/static/main/assets/tether/tether.min.js"></script>
  <script src="/static/main/assets/smoothscroll/smooth-scroll.js"></script>
  <script src="/static/main/assets/dropdown/js/nav-dropdown.js"></script>
  <script src="/static/main/assets/dropdown/js/navbar-dropdown.js"></script>
  <script src="/static/main/assets/touchswipe/jquery.touch-swipe.min.js"></script>
  <script src="/static/main/assets/theme/js/script.js"></script>


</body>
</html>

gazua/templates/main/page4.html
<!-- {% load static %}



<div style='width:50%; margin: auto;'>
  <img src="{% static 'mldl_main/images/iris_' %}{{predict_result}}.jpg" class="img-subject"/>
<div>

<div style='text-align: center;'>
  <h1>The predicted class is <span class="predicted-class">{{ predict_result }}</span></h1>
</div>

<div style='text-align: center; margin-top:3em; margin-bottom:4em;'>
  <p><a href="../">Return to previous page</a></p>
  <p><a href="../../">Return to home</a></p>
</div>


{% endblock %} -->

gazua/templates/main/resource.html
{%load static%}

<!DOCTYPE html>
<html  >
<head>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <!-- Site made with Mobirise Website Builder v4.12.4, https://mobirise.com -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v4.12.4, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="/static/main/assets/images/ant-1.png" type="image/x-icon">
  <meta name="description" content="Web Site Creator Description">


  <title>Analysis</title>
  <link rel="stylesheet" href="/static/main/assets/web//static/main/assets/mobirise-icons/mobirise-icons.css">
  <link rel="stylesheet" href="/static/main/assets/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="/static/main/assets/bootstrap/css/bootstrap-grid.min.css">
  <link rel="stylesheet" href="/static/main/assets/bootstrap/css/bootstrap-reboot.min.css">
  <link rel="stylesheet" href="/static/main/assets/tether/tether.min.css">
  <link rel="stylesheet" href="/static/main/assets/dropdown/css/style.css">
  <link rel="stylesheet" href="/static/main/assets/theme/css/style.css">
  <link rel="preload" as="style" href="/static/main/assets/mobirise/css/mbr-additional.css"><link rel="stylesheet" href="/static/main/assets/mobirise/css/mbr-additional.css" type="text/css">



</head>
<body>
  <section class="menu cid-sy0zTxd0AQ" once="menu" id="menu1-9">


    <nav class="navbar navbar-expand beta-menu navbar-dropdown align-items-center navbar-fixed-top navbar-toggleable-sm">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <div class="hamburger">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </div>
        </button>
        <div class="menu-logo">
            <div class="navbar-brand">
                <span class="navbar-logo">
                    <a href="../">
                         <img src="/static/main/assets/images/ant-1.png" alt="Mobirise" title="" style="height: 3.8rem;">
                    </a>
                </span>
                <span class="navbar-caption-wrap"><a class="navbar-caption text-white display-4" href="../">
                        Gazua</a></span>
            </div>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav nav-dropdown" data-app-modern-menu="true"><li class="nav-item">
                    <a class="nav-link link text-white display-4" href="">
                        <span class="mbri-home mbr-iconfont mbr-iconfont-btn"></span>
                        Resource
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link link text-white display-4" href="../aboutus"><span class="mbri-search mbr-iconfont mbr-iconfont-btn"></span>

                        About Us
                    </a>
                </li></ul>
            <div class="navbar-buttons mbr-section-btn"><a class="btn btn-sm btn-primary display-4" href="../ml_analysis"><span class="mbri-success mbr-iconfont mbr-iconfont-btn"></span>

                    Try It Now!
                </a></div>
        </div>
    </nav>
</section>

    <section class="counters3 counters cid-sy0AacDi98" id="counters3-2">
    <div class="container pt-4 mt-2">

      <div class="container">

          <!-- <h1>Simple hover effects with <code>raw data</code></h1> -->
          <button class="fill" onClick="window.open('https://opendart.fss.or.kr/intro/main.do')">전자공시시스템</button>
          <button class="fill" onClick="window.open('https://github.com/FinanceData/OpenDartReader')">OpenDartReader</button>
          <button class="fill" onclick="window.open('https://github.com/FinanceData/FinanceDataReader')">FinanceDataReader</button>
          <button class="fill" onclick="window.open('https://github.com/FinanceData/marcap')">시가총액 데이터셋</button>

        </div>


      </div>
</div>




  </div>
</section>


  <section class="engine"><a href="https://mobirise.info/l">free site templates</a></section><script src="/static/main/assets/web//static/main/assets/jquery/jquery.min.js"></script>
  <script src="/static/main/assets/popper/popper.min.js"></script>
  <script src="/static/main/assets/bootstrap/js/bootstrap.min.js"></script>
  <script src="/static/main/assets/tether/tether.min.js"></script>
  <script src="/static/main/assets/smoothscroll/smooth-scroll.js"></script>
  <script src="/static/main/assets/dropdown/js/nav-dropdown.js"></script>
  <script src="/static/main/assets/dropdown/js/navbar-dropdown.js"></script>
  <script src="/static/main/assets/touchswipe/jquery.touch-swipe.min.js"></script>
  <script src="/static/main/assets/theme/js/script.js"></script>


</body>
</html>